### ISSUE TITLE
End screen not displaying failed hashes correctly

### ISSUE THREAD

**Issue by epicEaston197** [GuVAnj8Gv3RJ/NeosAccountDownloader#113]
the spacing between these pages of data are so far apart
The spacing should be based off of text content

![image](https://github.com/GuVAnj8Gv3RJ/NeosAccountDownloader/assets/76523692/bc0a605f-0c06-4c9e-8670-ffd6f2634f33)

**Comment by GuVAnj8Gv3RJ** [comment]
Thanks for your report, this will be resolved in the next release.
