### ISSUE TITLE
Add .json extension to json files in Assets and make them humanly readable

### ISSUE THREAD

**Issue by Nytra** [GuVAnj8Gv3RJ/NeosAccountDownloader#116]
Stiefel's fork (https://github.com/stiefeljackal/NeosAccountDownloaderGPL) adds ".metadata.json" extension to json files instead of leaving them with no extension and makes them humanly readable.

(Currently these files are left in some binary format with no extension so they are not humanly readable. You can tell they are json because it says json in the file header)

**Comment by GuVAnj8Gv3RJ** [comment]
Thanks I'll take a look, there are certainly some files we have left to identify.

**Comment by stiefeljackal** [comment]
@GuVAnj8Gv3RJ This is just metadata from Neos of the asset file that I store for each asset (mime type from Neos and stored extension from AssetUri or ThumbnailUri) to ensure that metadata from Neos is not lost or misinterpreted by the file mime detection. This is not an asset file itself, so you can ignore as I believe your mime detection should detect json files. If you do want to store this metadata, then go ahead.

**Comment by GuVAnj8Gv3RJ** [comment]
I concur with your findings. I don't intend to make this a feature here but if there is lots of requests for it I might re-consider.

Thank you

**Comment by Nytra** [comment]
I mean there is at least one file with "metadata.json" in the file header in my latest account backup and it has no extension. So they do exist and are being downloaded into the Assets folder. This backup was made using GuVA's version of the tool not Stiefel's.
