### ISSUE TITLE
Regarding the FR locale

### ISSUE THREAD

**Issue by SectOLT** [GuVAnj8Gv3RJ/NeosAccountDownloader#125]
Not really an issue, but just a statement.

I am known as Mera, and I did do the original French translation as listed on the [v1.1.0](https://github.com/GuVAnj8Gv3RJ/NeosAccountDownloader/releases/tag/v1.1.0) release

I'll likely translate it more soon too. But for now, I thought I'd mention it for the sake of contributions listing

**Comment by GuVAnj8Gv3RJ** [comment]
Thank you!

**Comment by GuVAnj8Gv3RJ** [comment]
@all-contributors please add @SectOLT for translation

**Comment by GuVAnj8Gv3RJ** [comment]
All sorted, if you update the FR locale please make a PR.

Thank you!
