### ISSUE TITLE
Backing up linked folders not in account

### ISSUE THREAD

**Issue by Architector4** [GuVAnj8Gv3RJ/NeosAccountDownloader#14]
It may be useful to some to back up contents of folders the user has links to in their inventory. And possibly of folders linked in there too.

It would be really cool to have a maximum recursion depth setting one could put in to back up these folders too, with a warning that this can easily balloon in size.

**Comment by epicEaston197** [comment]
okay So what would you do if a folder linked to itself?
This would result in it just grabbing itself infinitely

**Comment by Architector4** [comment]
I'm not the dev of this program, but I imagine it shouldn't be hard to keep track of which folders were already visited and store just the link itself if it points to one such folder?

That, or at least rely on the maximum recursion depth setting provided there. Neos assets are uniquely identified as far as I understand, so a few recursions into the same folder shouldn't be too much of a problem besides resulting in a bunch of repeated metadata.

**Comment by GuVAnj8Gv3RJ** [comment]
This won't be supported sorry.
