### ISSUE TITLE
Records that are Featured Worlds are not being fetched

### ISSUE THREAD

**Issue by stiefeljackal** [GuVAnj8Gv3RJ/NeosAccountDownloader#192]
In the current implementation, records that are featured worlds are not being fetched by the tool. That was noticed by the Creator Jam (CJ) group that I belong in.

**Comment by GuVAnj8Gv3RJ** [comment]
Null strikes again https://www.infoq.com/presentations/Null-References-The-Billion-Dollar-Mistake-Tony-Hoare/

**Comment by GuVAnj8Gv3RJ** [comment]
I spoke to soon, standby
