### ISSUE TITLE
Missing BMPCUBE file extension

### ISSUE THREAD

**Issue by stiefeljackal** [GuVAnj8Gv3RJ/NeosAccountDownloader#193]
The .bmpcube file extension is missing. I discovered this when testing out with the CJ group as it has these type of files and confirmed as a recognized file in the Neos client.

Header: `07 42 6D 70 43 75 62 65 02`
MIME: cubemap/bitmapx

**Comment by GuVAnj8Gv3RJ** [comment]
Thanks for the header!
