### ISSUE TITLE
Download failures - Object reference not set to instance of an object

### ISSUE THREAD

**Issue by EuphieEuphoria** [GuVAnj8Gv3RJ/NeosAccountDownloader#202]
Receiving an error when attempting to download my database: Your Download has failed due to Object reference not set to an instance of an object..

Additionally, around half way through, the downloader began downloading Neos files into the downloader's installation directory, no input was made during the entire process.

![image](https://github.com/GuVAnj8Gv3RJ/NeosAccountDownloader/assets/101027344/e66bf349-57be-46e6-b4d9-f1ac9de171e3)

![image](https://github.com/GuVAnj8Gv3RJ/NeosAccountDownloader/assets/101027344/29fa7653-47d9-42a4-a5d3-97fe6510000b)

[20230912_202508-DESKTOP-K4OIUFU-1.11.1+6062335954-.log](https://github.com/GuVAnj8Gv3RJ/NeosAccountDownloader/files/12592212/20230912_202508-DESKTOP-K4OIUFU-1.11.1%2B6062335954-.log)

**Comment by GuVAnj8Gv3RJ** [comment]
Thank you for your report, We will investigate

**Comment by GuVAnj8Gv3RJ** [comment]
We've resolved this in #213 and the fix will be included in the next release.

**Comment by GuVAnj8Gv3RJ** [comment]
@all-contributors please add @EuphieEuphoria for bugs
