### ISSUE TITLE
`IAccountDataGatherer` is performing an operation that `IAccountDataStore` should be doing (Separation of Concerns)

### ISSUE THREAD

**Issue by stiefeljackal** [GuVAnj8Gv3RJ/NeosAccountDownloader#23]
The interface `IAccountDataGatherer` contains a method called `DownloadAsset` that is currently being used to download the asset stream as a file onto the file system. Any class that is solely implementing `IAccountDataGatherer` should not be doing this! If anything, a class that implements `IAccountDataGatherer` should only be gathering data that can be handed off to a object that implements `IAccountDataStore`. To address the issue of not following separation of concerns, the `DownloadAsset` method should be moved over to `IAccountDataGatherer` while a new method (perhaps `FetchAssetStream` or something) should be added to `IAccountDataGatherer` that fetches and returns the asset stream. That way, the storer can do whatever it wants with the stream whether that be to store it on the file system or something else.

**Comment by GuVAnj8Gv3RJ** [comment]
Code architecture in open source projects is largely a "help wanted" or a "when it becomes an issue" item. 

I agree in principle but most of this only matters if the downloader starts to do more with both of those interfaces. We don't really have a "more" defined right now so this is getting a low priority too.

**Comment by stiefeljackal** [comment]
That's fine. I just wanted to make note of it. When the time comes, it can be decided if the interfaces need to be examined again. I appreciate the fact that you are still considering this for the future.

**Comment by GuVAnj8Gv3RJ** [comment]
Thanks for the feedback.

@all-contributors please add @stiefeljackal for ideas
