### ISSUE TITLE
NeosAccountDownloader Keeps Crashing

### ISSUE THREAD

**Issue by SectOLT** [GuVAnj8Gv3RJ/NeosAccountDownloader#28]
Hai ! I am experiencing issues with the downloader tool at the time of writing this.

I download the latest release for this tool
I launch the tool, enter my NeosVR Username, as well as my password
Then i enter my 2 Factor Authentication code

After that, it freeze for a few seconds, then the tool just crash itself.

Maybe it's due to an API change on Neos' end ? Should maybe look into that

**Comment by stiefeljackal** [comment]
@SectOLT I tested with 2FA enabled on a test account and it progressed as expected. Can you post logs for the repository maintainer? It will help the maintainer and other contributors figure out the source of the issue. You can find your logs at `%LOCALAPPDATA%\GuVAnj8Gv3RJ\Neos Account Downloader`.

**Comment by stiefeljackal** [comment]
Created Pull Request #29.

**Comment by SectOLT** [comment]
> Still post logs, but I believe I was able to reproduce your issue. I believe what happened is that you entered the wrong one-time code (perhaps it expired at just the right moment). When I entered an incorrect code, I was able to see the app freeze and then crash. I see the spot where the exception is thrown, so it should be fixable.

I use a code generated by the authenticator app at the time of entering, that code was valid, as well as my account username and password. I can confirm that since the same copy paste password was used to login to NeosVR few days prior.

And logs attached below
[DESKTOP-R1O2UDH-1.5.0+5302484815-20230718.log](https://github.com/GuVAnj8Gv3RJ/NeosAccountDownloader/files/12088122/DESKTOP-R1O2UDH-1.5.0%2B5302484815-20230718.log)

**Comment by stiefeljackal** [comment]
> > Still post logs, but I believe I was able to reproduce your issue. I believe what happened is that you entered the wrong one-time code (perhaps it expired at just the right moment). When I entered an incorrect code, I was able to see the app freeze and then crash. I see the spot where the exception is thrown, so it should be fixable.
> 
> I use a code generated by the authenticator app at the time of entering, that code was valid, as well as my account username and password. I can confirm that since the same copy paste password was used to login to NeosVR few days prior.
> 
> And logs attached below [DESKTOP-R1O2UDH-1.5.0+5302484815-20230718.log](https://github.com/GuVAnj8Gv3RJ/NeosAccountDownloader/files/12088122/DESKTOP-R1O2UDH-1.5.0%2B5302484815-20230718.log)
> 
> First attempt was prior attempt that failed. I thought the tool was outdated so i redownloaded it to make sure, same issue happened.

Damn. The logs really do not say much, and the maintainer really did not add a proper header in the log file to indicate the start of a run instance or have separate log files for different run instances.

Anyway, both routes (one where the TOTP is wrong and one where something went wrong on the API end) lead to an exception being thrown that causes the app to crash. The pull request that I made and mentioned above should address that. If you want to clone the PR, compile it, and run it, then you will more than likely see the error that you are getting.

**Comment by GuVAnj8Gv3RJ** [comment]
Fixed in: https://github.com/GuVAnj8Gv3RJ/NeosAccountDownloader/pull/29
