### ISSUE TITLE
Locale

### ISSUE THREAD

**Issue by GuVAnj8Gv3RJ** [GuVAnj8Gv3RJ/NeosAccountDownloader#3]
1. Duplicate: https://github.com/GuVAnj8Gv3RJ/NeosAccountDownloader/blob/main/AccountDownloader/Properties/Resources.resx
2. Save it as Resources.`<code>`.resx
3. Translate
4. PR it

**Comment by stiefeljackal** [comment]
Even though a good amount of the application is translated, there are still other components that are still untranslated. How are you going to solve this issue?

![image](https://github.com/GuVAnj8Gv3RJ/NeosAccountDownloader/assets/20023996/7cbbb6ff-3495-4a1d-828e-01569d70c8f8)

This is a French translation; why is the entirety of this not translated? How come you did not provide additional elements in the Resources file to translate this?

**Comment by GuVAnj8Gv3RJ** [comment]
Locale is community driven. I can machine translate but don't want to rely on that.

**Comment by stiefeljackal** [comment]
I have received info that someone who can do French translations wanted to (and still is happy to) translate the English words and phrases in that dialog above. However, you specified that cannot be done due to the "design of the application." So what is your actual answer? Honestly, I do not think you want to put in the work to provide the availability for other translators to translate other strings unless you put those in the Resource files.

**Comment by GuVAnj8Gv3RJ** [comment]
That translator should make a separate issue describing their problems and we'll do our best to resolve them. 

I personally use: https://marketplace.visualstudio.com/items?itemName=TomEnglert.ResXManager to manage the locale files.

**Comment by ProbablePrime** [comment]
![image](https://github.com/GuVAnj8Gv3RJ/NeosAccountDownloader/assets/8791132/2d0c5d16-5376-4881-9a7c-31f091059d5a)

French appears complete. 

If a string is missing from the EN file, its unlocalalizable for any locale. This is very similar to how Neos does things where some areas periodically go through improvements to become localizable. I haven't touched the Library portion of the code here in terms of localization at all. When I do, i'll update things here.

**Comment by GuVAnj8Gv3RJ** [comment]
Closing, localization instructions are now in the readme.

Additional localization issues need to occur in their own issue.
