### ISSUE TITLE
Strings Should Auto-refresh When Language Changes

### ISSUE THREAD

**Issue by stiefeljackal** [GuVAnj8Gv3RJ/NeosAccountDownloader#32]
I know you stated somewhere that the strings do not refresh when the language is selected until progressing to the next screen. I believe this should be fixed. I get it that the default language that the computer is set to should be automatically picked up by the application; however, this sort of thing would not be acceptable in an industry application and will not be acceptable to the Neos community.

Please fix this.

**Comment by GuVAnj8Gv3RJ** [comment]
This is possible but a low priority currently.

**Comment by GuVAnj8Gv3RJ** [comment]
The options here are basically:
1. Reload/Refresh the view when the locale changes while preserving state(re-using View Models)
1. Write a custom version of the Resources.Designer generator that supports INotifyChanged and is not static

1 sounds easier, but I'm not sure if there would be any problems from it so will have to test.

**Comment by GuVAnj8Gv3RJ** [comment]
We now do 1.
