### ISSUE TITLE
Stop Auto-populating "NeosDownload" to Folder Path if the Folder Selected Already Contains My Backup

### ISSUE THREAD

**Issue by stiefeljackal** [GuVAnj8Gv3RJ/NeosAccountDownloader#33]
It is getting very annoying that I have to clear out "NeosDownload" in the file path textbox because I decided that I wanted my backup folder to be called something else. When selecting the folder, the **Neos Account Downloader** should peek at the folder contents and know automatically it is the same folder used for my backups and NOT append "NeosDownload" to the end of it.

**Comment by GuVAnj8Gv3RJ** [comment]
There's a partial fix in #71 which will prevent recursion of NeosDownload. A better fix will be later on.

**Comment by GuVAnj8Gv3RJ** [comment]
This is resolved now. 

I want to add a "Marker" file with version information of the version of the downloader used to make a local data store though. This will prevent any incompatibilities later and allow us to code custom handling depending on what type of Local database we have.
