### ISSUE TITLE
Tool Does Not Convert AnimJ Imported Files

### ISSUE THREAD

**Issue by stiefeljackal** [GuVAnj8Gv3RJ/NeosAccountDownloader#35]
When working with AnimJ and importing them into Neos, AnimJ is converted to AnimX. The tool downloads them as AnimX; however, it does not convert them back to AnimJ. I believe these files should be converted back to AnimJ.

**Comment by GuVAnj8Gv3RJ** [comment]
Leaving assets in their original form is part of the design here. Conversion to other data types is for other tools as described in the readme.

Due to this, closing as not planned.
