### ISSUE TITLE
Old Deleted Records on Neos Are Not Deleted in Backup

### ISSUE THREAD

**Issue by stiefeljackal** [GuVAnj8Gv3RJ/NeosAccountDownloader#37]
When one deletes an inventory item or world on Neos, that action leads to the "deletion" of the item in the cloud (or at least the deletion of the record). If I have started an instance of the Neos Account Downloader app before the deletion of the item, the record metadata and the asset are downloaded as expected. However, if I should start an instance of the downloader AFTER deleting the item, then I expect the downloader to remove the files associated with that record. However, it does not. This leaves the user with record files and asset files that the user does not want, so the tool should have a way to remove these items.

**Comment by GuVAnj8Gv3RJ** [comment]
This won't be supported unfortunately. This is a backup tool not a synchronization tool.

**Comment by stiefeljackal** [comment]
Then you better add a disclaimer. I’m just thinking as a User.
