### ISSUE TITLE
Convert 7zbson to JSON

### ISSUE THREAD

**Issue by stiefeljackal** [GuVAnj8Gv3RJ/NeosAccountDownloader#44]
As you mentioned previously in #17 .

> Thanks for your update. I just want users to be able to see textures, sfx etc in their file browser at the moment. That's why we need the file extension.

In order for users to see the contents of a 7zbson, you will need to add something that will convert 7zbson to json.

**Comment by GuVAnj8Gv3RJ** [comment]
As described in: https://github.com/GuVAnj8Gv3RJ/NeosAccountDownloader/issues/35

We don't intend to convert files to better/easier formats here. That's the goal of someone else as mentioned in the readme.

For mime/file extension, that's just a personal pet peeve. File extensions are needed but being missed here.
