### ISSUE TITLE
Think As a User

### ISSUE THREAD

**Issue by stiefeljackal** [GuVAnj8Gv3RJ/NeosAccountDownloader#45]
I’m seeing a lot of issues being closed (#30 and #37 to name a few) that involve user friendliness and acceptance. I don’t know your background, but I would consider putting the user first. #30 should not be that hard to implement. If you want the Neos Community to accept this tool, you must put the user first.

**Comment by GuVAnj8Gv3RJ** [comment]
This is not an actionable item(bug, feature etc) so is being closed.

We do our best to think of users when we can.

**Comment by stiefeljackal** [comment]
This is my only way of communicating to you. Thank you for at least stating that last sentence.
