### ISSUE TITLE
README: Include Resolved Issue Reporters as Contributors

### ISSUE THREAD

**Issue by stiefeljackal** [GuVAnj8Gv3RJ/NeosAccountDownloader#54]
For those that submitted an issue that was resolved (ex. #26 and #28 ), shouldn't they be included in the contributor list as well?

**Comment by GuVAnj8Gv3RJ** [comment]
@all-contributors
Please add @bontebok for bugs.
Please add @SectOLT for bugs.

**Comment by GuVAnj8Gv3RJ** [comment]
ThaNKS!
