### ISSUE TITLE
Help -> About no longer opens in 1.6.0

### ISSUE THREAD

**Issue by bontebok** [GuVAnj8Gv3RJ/NeosAccountDownloader#57]
Saw the release notes for 1.6.0 saying credits were in the Help -> About, went to try it and nothing happened. Checked version 1.5.0 and the Help -> About worked.

**Comment by stiefeljackal** [comment]
About seems to work when I complied the source.

<img width="596" alt="image" src="https://github.com/GuVAnj8Gv3RJ/NeosAccountDownloader/assets/20023996/5a377bf0-b71b-4a1b-af3b-ed388dd5f4c9">

Window is cutting off the contributors though... I'm going to submit that as a separate issue.

Anyway, I'm going to check the one in the Release section.

**Comment by stiefeljackal** [comment]
Yeah. The `exe` that is in the zip folder in the [v1.6.0 Release Page](https://github.com/GuVAnj8Gv3RJ/NeosAccountDownloader/releases/tag/v1.6.0) is bad. It is not opening the About window. The easy fix for this is for @GuVAnj8Gv3RJ to recompile it and redeploy.

**Comment by GuVAnj8Gv3RJ** [comment]
Should be fixed in #59 I'll check the GitHub CI version on the next build but worked locally(much faster too :D)

Thanks!

**Comment by stiefeljackal** [comment]
You're welcome!

**Comment by bontebok** [comment]
@GuVAnj8Gv3RJ The recent release v1.7.0 still exhibits this issue.

**Comment by GuVAnj8Gv3RJ** [comment]
Thanks, looks like this is a CI/CD issue, re-opening.

**Comment by GuVAnj8Gv3RJ** [comment]
I put in a log line on the main part of contributor fetching with a try catch included. This should give us information and also allow the window to load.

If this happens of course the contributors won't appear but we'll be further along on our journey in understanding what's going on.

**Comment by GuVAnj8Gv3RJ** [comment]
`2023-07-29 14:02:55.744 -07:00 [ERR] Failed to load contributor information due to: The resource avares://Neos Account Downloader/Assets/.all-contributorsrc could not be found.`

Great, now we know what's up.

About window will open in 1.8 but contributor list is blank.

**Comment by GuVAnj8Gv3RJ** [comment]
https://github.com/GuVAnj8Gv3RJ/NeosAccountDownloader/actions/runs/5702407141/job/15454067731#step:5:39

No errors. 

I'll just put something in the CI.

**Comment by GuVAnj8Gv3RJ** [comment]
Fixed in 1.8.1
