### ISSUE TITLE
About Window is Cutting Off Contributors

### ISSUE THREAD

**Issue by stiefeljackal** [GuVAnj8Gv3RJ/NeosAccountDownloader#58]
When the About window opens up, it is cutting off some of the contributors.

![image](https://github.com/GuVAnj8Gv3RJ/NeosAccountDownloader/assets/20023996/346a88d3-93eb-402c-839a-8187b388ee71)

**Comment by GuVAnj8Gv3RJ** [comment]
@all-contributors please add @stiefeljackal for bugs 

Fixed in #59

**Comment by stiefeljackal** [comment]
Thank you.
