### ISSUE TITLE
`*.Storage.json` Files Only Have `null` Content

### ISSUE THREAD

**Issue by stiefeljackal** [GuVAnj8Gv3RJ/NeosAccountDownloader#62]
Any `*.Storage.json` files created for Groups and Members of Groups all contain `null` in them. What is the purpose of these files? Should they contain the number of bytes free and used for a group and for a member?

<img width="629" alt="image" src="https://github.com/GuVAnj8Gv3RJ/NeosAccountDownloader/assets/20023996/655e768e-fbfb-4357-9f2d-60b352cb8ce3">

Additionally, what is with the following endpoints?

```
api/users/(userId)/storage
api/groups/(groupId)/storage
api/groups/(groupId)/members/(userId)/storage
```
These endpoints are being fetched with the GET verb from methods `GetStorage` and `GetMemberStorage` in [CloudXInterfaceExtensions.cs](https://github.com/GuVAnj8Gv3RJ/NeosAccountDownloader/blob/main/AccountDownloaderLibrary/Extensions/CloudXInterfaceExtensions.cs). Those methods are called when the downloader is gathering the storage information for the group and its members, but they are returning `null` back. Testing these endpoints with the CloudX client is also producing 404.

<img width="802" alt="image" src="https://github.com/GuVAnj8Gv3RJ/NeosAccountDownloader/assets/20023996/032a4263-f1db-4542-87fb-7a61a317ae22">

These endpoints are nowhere to be found in CloudX.Shared, and the models `Storage`, `QuotaShare`, `QuotaSource`, and `QuotaType` in [Storage.cs](https://github.com/GuVAnj8Gv3RJ/NeosAccountDownloader/blob/main/AccountDownloaderLibrary/Models/Storage.cs) are used to map to the returned JSON from these endpoints.

**Comment by GuVAnj8Gv3RJ** [comment]
These files were requested by a user and sometimes appear in certain situations. We can update the code to not write them when they are not present though.

Thanks!

**Comment by stiefeljackal** [comment]
They all contain `null`. The best way to store storage information would be to use the other endpoints. They are exposed with a method from CloudXInterface, but I cannot remember which one. Here are the endpoints that might be better to use:

<img width="757" alt="image" src="https://github.com/GuVAnj8Gv3RJ/NeosAccountDownloader/assets/20023996/183b7f90-45f8-41c3-b0f3-17d51ce8a5b0">

**Comment by GuVAnj8Gv3RJ** [comment]
The data stored is different and sometimes not null. I will update the code to only store when It is not null.

Thank you.

**Comment by stiefeljackal** [comment]
But that does not make sense how it would sometimes not be null. Those endpoints are not available in CloudX.Shared, so no one on Neos can interact with those endpoints:

```
api/users/(userId)/storage
api/groups/(groupId)/storage
api/groups/(groupId)/members/(userId)/storage
```

Here are images of debugging this particular area:

<img width="565" alt="image" src="https://github.com/GuVAnj8Gv3RJ/NeosAccountDownloader/assets/20023996/1b7ae1f7-9eb3-4899-a596-b846ae4e23e5">

<img width="454" alt="image" src="https://github.com/GuVAnj8Gv3RJ/NeosAccountDownloader/assets/20023996/307ef1a0-ecb0-413a-977f-791c07ff0a6f">

The only situation that these endpoints could be reached is if this tool is being used elsewhere internally where these endpoints are understood.

**Comment by GuVAnj8Gv3RJ** [comment]
Fixed in: https://github.com/GuVAnj8Gv3RJ/NeosAccountDownloader/commit/a85b727bbf084f9e4d90ea087d470d888df30459
