### ISSUE TITLE
Application is Using Azure Endpoints And Not CloudFlare Endpoints

### ISSUE THREAD

**Issue by stiefeljackal** [GuVAnj8Gv3RJ/NeosAccountDownloader#7]
I noticed that the application is using the Azure endpoints instead of the CloudFlare ones, and this might be due to the fact that it is using the older DLL. Using the CloudFlare ones will improve the download speed for most. Instead of relying on its own set of DLLs, perhaps this should be changed to point directly to the DLLs in the Neos folder instead to somewhat future proof this incase a sudden update occurs.

**Comment by GuVAnj8Gv3RJ** [comment]
fixed in: https://github.com/GuVAnj8Gv3RJ/NeosAccountDownloader/commit/22262ab05976c79626ab43c516790ea693c17ac9

**Comment by stiefeljackal** [comment]
That's good, but you **really** should reference the DLLs in the Neos folder in case another small update like this occurs.

**Comment by GuVAnj8Gv3RJ** [comment]
I find that unlikely.

PRS welcome though, should just be another webrequest in the build action

**Comment by stiefeljackal** [comment]
I know it is unlikely. There is another reason why I am pushing. If this is the route you are going to tread on, then so be it.
