### ISSUE TITLE
Investigate timeout issues

### ISSUE THREAD

**Issue by GuVAnj8Gv3RJ** [GuVAnj8Gv3RJ/NeosAccountDownloader#72]
![image](https://github.com/GuVAnj8Gv3RJ/NeosAccountDownloader/assets/132167543/c732d97e-4325-4eca-9258-e05626a5db6e)

This is one of two things probably:
1. Big chunky assets
2. Neos Cloud slowing down over the weekends or whatever

For now we can raise the timeout, expose that as a user setting.

But ideally we'd retry these. But retries are a harder topic.

**Comment by stiefeljackal** [comment]
It's definitely during the weekends (Fridays and Saturdays) where the Neos Cloud experiences too many 429s and slowdowns. I and @bontebok were monitoring this when it first started, but I gradually stopped (may still want to do that to see if it is getting worse).

Anyway, raising the timeout and adding retries can help with this. I would lean more towards retries as you do have assets in a job-like class right now. It would not be too difficult to retry and push the job back in the queue as long as you have something where the job will terminate and discarded after a number of retries.

**Comment by GuVAnj8Gv3RJ** [comment]
Ok i've doubled the timeouts for now, will do retries via another issue
