### ISSUE TITLE
Localized strings cause problems when longer than original ones in English

### ISSUE THREAD

**Issue by rampa3** [GuVAnj8Gv3RJ/NeosAccountDownloader#74]
Localized strings can cause layout problems, if the language the program is being localized to has longer translated strings than the original ones.

For example on the login page:
![image](https://github.com/GuVAnj8Gv3RJ/NeosAccountDownloader/assets/68955305/8eb79cc0-13fa-4790-b816-12a87b37411f)

Possible solutions that I can think of now, are responsive design based of the longest string for forms or other "table" layouts, or just having the fields put to the far right, but that would create big gaps between them and their labels.

**Comment by GuVAnj8Gv3RJ** [comment]
Login was of course one of the first pages I made, so It might be the only one with the issue. Please check others if you can.

Thank you!

**Comment by rampa3** [comment]
All the other pages I seen with localization during testing so far, only the login is having string length troubles. Are there any views that normally don't show to check?

Btw, did not tested how localized strings look in about window, since I am on Linux rn, and it doesn't want to open in the latest release here...

**Comment by stiefeljackal** [comment]
The About window is currently facing issues in all releases. Please see #57.

**Comment by GuVAnj8Gv3RJ** [comment]
Grids are terrible
