### ISSUE TITLE
English language option no longer available when set to another language by default

### ISSUE THREAD

**Issue by 5H4D0W-X** [GuVAnj8Gv3RJ/NeosAccountDownloader#89]
![image](https://github.com/GuVAnj8Gv3RJ/NeosAccountDownloader/assets/99607717/0ef7c9d8-cf9c-4fa6-afbe-d40b98747295)

(My system language is set to German)

**Comment by GuVAnj8Gv3RJ** [comment]
@all-contributors please add @5H4D0W-X for bugs.
