### ISSUE TITLE
Typo in LocalAccountDataStore

### ISSUE THREAD

**Issue by ProbablePrime** [GuVAnj8Gv3RJ/NeosAccountDownloader#90]
https://github.com/GuVAnj8Gv3RJ/NeosAccountDownloader/blob/main/AccountDownloaderLibrary/Implementations/LocalAccountDataStore.cs#L184

That should have {}'s

**Comment by GuVAnj8Gv3RJ** [comment]
Thanks, will take care of

**Comment by GuVAnj8Gv3RJ** [comment]
![image](https://github.com/GuVAnj8Gv3RJ/NeosAccountDownloader/assets/132167543/f6e84c01-e1cd-4227-9fa1-9cee13ff1555)

🤦 

This caused some mess on my personal download. Thank you.

@all-contributors please add @ProbablePrime for bugs.
