### ISSUE TITLE
Adopt a code of conduct/guidelines

### ISSUE THREAD

**Issue by ProbablePrime** [GuVAnj8Gv3RJ/NeosAccountDownloader#95]
Many repositories have these and they help with issues.

I particularly like: https://github.com/processing/p5.js/blob/main/CODE_OF_CONDUCT.md but that is just a suggestion

**Comment by GuVAnj8Gv3RJ** [comment]
I have added one that GitHub let me add easily. It is very similar to p5's and others that i've read.
